#! /usr/bin/env bash

# Expose proxied secrets to the first sandbox for this PWD

# Support symlinked agents config
AGENTS_DIR="$(realpath $HOME/.agents)"

firstId="$(msb ps --label "msb.pwd=$PWD" --quiet | head -1)"

if [[ -n "$firstId" ]]; then
  msb modify
    --secret "PERPLEXITY_API_KEY@api.perplexity.ai" \
    --secret "OPENROUTER_API_KEY@openrouter.ai" \
    --secret "INCEPTION_API_KEY@api.inceptionlabs.ai" \
    --mount-dir "${AGENTS_DIR}:/root/.agents:ro" \
    "$@" \
    "$firstId"
else
  echo "No sandbox found for this PWD" >&2
fi
